installation:
  version: 6.0.0-Beta.5
  installDate: 2026-02-03T12:39:35.461Z
  lastUpdated: 2026-02-03T12:39:35.461Z
modules:
  - name: core
    version: 6.0.0-Beta.5
    installDate: 2026-02-03T12:39:35.062Z
    lastUpdated: 2026-02-03T12:39:35.062Z
    source: built-in
    npmPackage: null
    repoUrl: null
  - name: tea
    version: 0.1.1-beta.3
    installDate: 2026-02-03T12:39:35.039Z
    lastUpdated: 2026-02-03T12:39:35.461Z
    source: external
    npmPackage: bmad-method-test-architecture-enterprise
    repoUrl: https://github.com/bmad-code-org/bmad-method-test-architecture-enterprise
ides:
  - codex
  - github-copilot
