installation:
  version: 6.0.0-Beta.7
  installDate: 2026-02-03T12:39:35.461Z
  lastUpdated: 2026-02-05T20:25:18.689Z
modules:
  - name: core
    version: 6.0.0-Beta.7
    installDate: 2026-02-03T12:39:35.062Z
    lastUpdated: 2026-02-05T20:25:18.443Z
    source: built-in
    npmPackage: null
    repoUrl: null
  - name: bmm
    version: 6.0.0-Beta.7
    installDate: 2026-02-05T20:25:16.878Z
    lastUpdated: 2026-02-05T20:25:18.443Z
    source: built-in
    npmPackage: null
    repoUrl: null
  - name: tea
    version: 0.1.1-beta.3
    installDate: 2026-02-03T12:39:35.039Z
    lastUpdated: 2026-02-05T20:25:18.689Z
    source: external
    npmPackage: bmad-method-test-architecture-enterprise
    repoUrl: https://github.com/bmad-code-org/bmad-method-test-architecture-enterprise
ides:
  - codex
  - github-copilot
